# Generated by Django 4.0.6 on 2022-08-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista_Familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.CharField(max_length=10, verbose_name='identificacion'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nacimiento',
            field=models.DateTimeField(verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='ocupacion',
            field=models.CharField(max_length=40, verbose_name='Ocupacion'),
        ),
    ]
