# Generated by Django 4.0.6 on 2022-08-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista_Familiares', '0002_alter_familiar_apellido_alter_familiar_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='nacimiento',
            field=models.DateField(verbose_name='fecha de nacimiento'),
        ),
    ]
