# Generated by Django 4.0.6 on 2022-08-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista_Familiares', '0003_alter_familiar_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=40, verbose_name='ocupacion'),
        ),
    ]
