# Generated by Django 4.0.6 on 2022-08-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista_Familiares', '0004_alter_familiar_apellido_alter_familiar_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.IntegerField(max_length=10, verbose_name='identificacion'),
        ),
    ]
