# Generated by Django 4.0.6 on 2022-08-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista_Familiares', '0005_alter_familiar_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.IntegerField(verbose_name='identificacion'),
        ),
    ]
